### ISSUE TITLE
Failed to register: Function failed to register: invalid runtime: Async

### ISSUE THREAD

**Issue by gongxh13** [OpenFunction/samples#111]
I deploy functio async pubsub demo, and I get below error:
![image](https://user-images.githubusercontent.com/44743148/220882126-c8dd4bf8-9da1-4fe7-9836-e1f37ab1f812.png)
```
kubectl logs serving-hbhs8-deployment-v200-jtwxp-59787c577d-68btk
2023/02/23 10:28:35 Failed to register: Function failed to register: invalid runtime: Async
```
My sub function yaml is:
```
apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: autoscaling-subscriber
spec:
  version: "v2.0.0"
  image: openfunctiondev/autoscaling-subscriber:latest

  serving:
    runtime: "async"
    scaleOptions:
      keda:
        scaledObject:
          pollingInterval: 15
          minReplicaCount: 0
          maxReplicaCount: 10
          cooldownPeriod: 60
          advanced:
            horizontalPodAutoscalerConfig:
              behavior:
                scaleDown:
                  stabilizationWindowSeconds: 45
                  policies:
                  - type: Percent
                    value: 50
                    periodSeconds: 15
                scaleUp:
                  stabilizationWindowSeconds: 0
    triggers:
      - type: kafka
        metadata:
          topic: "sample-topic"
          bootstrapServers: kafka-server-kafka-brokers.default.svc.cluster.local:9092
          consumerGroup: autoscaling-subscriber
          lagThreshold: "20"
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    inputs:
      - name: producer
        component: kafka-server
        topic: "sample-topic"
    pubsub:
      kafka-server:
        type: pubsub.kafka
        version: v1
        metadata:
          - name: brokers
            value: "kafka-server-kafka-brokers:9092"
          - name: authRequired
            value: "false"
          - name: allowedTopics
            value: "sample-topic"
          - name: consumerID
            value: "autoscaling-subscriber"
```
