### ISSUE TITLE
couldn't find output binding serving-fv9tm-bindings-httpz-m5cbd

### ISSUE THREAD

**Issue by uestczz** [OpenFunction/samples#132]
I'm trying the sample named `with-output-binding`, and function-front.yaml may confuse me. so I make my yaml based on the readme.  k8s  v1.26.0      openfunction/openfunction:v1.1.1
my serving config is as below:
‘‘‘
apiVersion: core.openfunction.io/v1beta2
 serving:
    scaleOptions:
      minReplicas: 0
      maxReplicas: 5
    outputs:
      - dapr:
          name: httpz
          operation: "post"
      - dapr:
          name: httpy
          operation: "get"
    bindings:
      httpz:
        type: bindings.http
        version: v1
        metadata:
          - name: url
            value: "http://10.0.0.127:14121/workwxsdk/proxy/service/corpid_to_opencorpid"
          - name: direction
            value: "output"
      httpy:
        type: bindings.http
        version: v1
        metadata:
          - name : url
            value: "http://10.0.0.127:30417/corp_customer/customer/info"
          - name: direction
            value: "output"
    template:
      containers:
        - name: function
          imagePullPolicy: IfNotPresent
    triggers:
      http:
        port: 8080
’’’

and my code is as below:
`		req := CorpIDToOpenReq{
			CorpID: "xxxxxxx",
		}
		data, _ := json.Marshal(req)
		bytes, err := ctx.Send("httpz", data)
		if err != nil {
			return ctx.ReturnOnInternalError(), err
		}
`
Then a error raised:
2023/09/07 02:04:14 httpz
2023/09/07 02:04:14 {httpz serving-fv9tm-bindings-httpz-m5cbd bindings.http map[] post}
2023/09/07 02:04:14 httpy
2023/09/07 02:04:14 {httpy serving-fv9tm-bindings-httpy-v2t64 bindings.http map[] get}
2023/09/07 02:04:14 [123 10 9 34 110 34 58 32 49 10 125]
2023/09/07 02:04:15 error invoking binding serving-fv9tm-bindings-httpz-m5cbd/post: rpc error: code = Internal desc = error when invoke output binding serving-fv9tm-bindings-httpz-m5cbd: couldn't find output binding serving-fv9tm-bindings-httpz-m5cbd

I print the output map, there's a key named httpz. and I want to invode a nodapr httpendpoint. so what's wrong with my code.

**Comment by wanjunlei** [comment]
Run the following command and paste the result.

```
kubectl get servings serving-fv9tm -n < namespace > -oyaml
kubectl get components -A
```

**Comment by uestczz** [comment]
@wanjunlei 
i update my function, so the name may changes.
2023/09/07 06:04:56 httpz
2023/09/07 06:04:56 {httpz serving-2xtn4-bindings-httpz-47wjs bindings.http map[] post}
2023/09/07 06:04:56 httpy
2023/09/07 06:04:56 {httpy serving-2xtn4-bindings-httpy-694tj bindings.http map[] get}
2023/09/07 06:04:56 [123 10 9 34 110 34 58 32 49 10 125]
2023/09/07 06:04:57 error invoking binding serving-2xtn4-bindings-httpz-47wjs/post: rpc error: code = Internal desc = error when invoke output binding serving-2xtn4-bindings-httpz-47wjs: couldn't find output binding serving-2xtn4-bindings-httpz-47wjs

kubectl get servings.core.openfunction.io serving-2xtn4 -oyaml
apiVersion: core.openfunction.io/v1beta2
kind: Serving
metadata:
  creationTimestamp: "2023-09-07T03:25:22Z"
  generateName: serving-
  generation: 1
  labels:
    openfunction.io/function: go-bind-http
  name: serving-2xtn4
  namespace: default
  ownerReferences:
  - apiVersion: core.openfunction.io/v1beta2
    blockOwnerDeletion: true
    controller: true
    kind: Function
    name: go-bind-http
    uid: 2cd34951-9d7d-459b-884e-a53e6bb63b47
  resourceVersion: "82349015"
  uid: cf808997-0c80-48ba-a97a-1b457579d26b
spec:
  bindings:
    httpy:
      ignoreErrors: false
      initTimeout: ""
      metadata:
      - name: url
        secretKeyRef:
          key: ""
          name: ""
        value: http://10.0.0.127:30417/corp_customer/customer/info
      - name: direction
        secretKeyRef:
          key: ""
          name: ""
        value: output
      type: bindings.http
      version: v1
    httpz:
      ignoreErrors: false
      initTimeout: ""
      metadata:
      - name: url
        secretKeyRef:
          key: ""
          name: ""
        value: http://10.0.0.127:14121/workwxsdk/proxy/service/corpid_to_opencorpid
      - name: direction
        secretKeyRef:
          key: ""
          name: ""
        value: output
      type: bindings.http
      version: v1
  image: uestczshen/go-bind-http:v1@sha256:b620b7bffbccc2ba077937f6edca46f383e91ea5010e02cca2b7280afb4898fa
  imageCredentials:
    name: push-secret
  outputs:
  - dapr:
      name: httpz
      operation: post
      type: bindings.http
  - dapr:
      name: httpy
      operation: get
      type: bindings.http
  scaleOptions:
    maxReplicas: 5
    minReplicas: 0
  template:
    containers:
    - imagePullPolicy: IfNotPresent
      name: function
      resources: {}
  triggers:
    http:
      port: 8080
      route:
        gatewayRef:
          name: openfunction
          namespace: openfunction
  version: v1.0.0
status:
  message: Running
  phase: Serving
  reason: Running
  resourceRef:
    dapr-proxy: serving-2xtn4-proxy-deployment-v100-swq6s
    dapr.io/component: serving-2xtn4-bindings-httpy-694tj,serving-2xtn4-bindings-httpz-47wjs
    serving.knative.dev/service: serving-2xtn4-ksvc-5w44p
  state: Running
  url: serving-2xtn4-ksvc-5w44p

kubectl get components -A
NAMESPACE   NAME                                 AGE
default     pubsub                               78d
default     serving-2xtn4-bindings-httpy-694tj   155m
default     serving-2xtn4-bindings-httpz-47wjs   155m
default     statestore                           78d

**Comment by uestczz** [comment]
@wanjunlei do you have wechat group, or online meeting?   I read the code of function "parseContext" in the repo functions-framework-go. but it just unmarshal the env data. so how are the outputs in yaml transformed to data in env.

**Comment by wanjunlei** [comment]
you can join our [discord channel](https://discord.gg/hG3yc6uAyC)

**Comment by uestczz** [comment]
@wanjunlei so could you please help me solve my problem? and I paste the result of your cmd.

**Comment by wanjunlei** [comment]
You need to add `httpz` to the `spec.bindings` like the `spec.bindings.httpy`

**Comment by uestczz** [comment]
@wanjunlei  there's also the same problem with httpy.
2023/09/07 07:55:57 error invoking binding serving-2xtn4-bindings-httpy-694tj/get: rpc error: code = Internal desc = error when invoke output binding serving-2xtn4-bindings-httpy-694tj: couldn't find output binding serving-2xtn4-bindings-httpy-694tj

the specs of httpz and httpy are the same.
```
spec:
  bindings:
    httpy:
      ignoreErrors: false
      initTimeout: ""
      metadata:
      - name: url
        secretKeyRef:
          key: ""
          name: ""
        value: http://10.0.0.127:30417/corp_customer/customer/info
      - name: direction
        secretKeyRef:
          key: ""
          name: ""
        value: output
      type: bindings.http
      version: v1
    httpz:
      ignoreErrors: false
      initTimeout: ""
      metadata:
      - name: url
        secretKeyRef:
          key: ""
          name: ""
        value: http://10.0.0.127:14121/workwxsdk/proxy/service/corpid_to_opencorpid
      - name: direction
        secretKeyRef:
          key: ""
          name: ""
        value: output
      type: bindings.http
      version: v1
  image: uestczshen/go-bind-http:v1@sha256:b620b7bffbccc2ba077937f6edca46f383e91ea5010e02cca2b7280afb4898fa
  imageCredentials:
    name: push-secret
  outputs:
  - dapr:
      name: httpz
      operation: post
      type: bindings.http
  - dapr:
      name: httpy
      operation: get
      type: bindings.http
  scaleOptions:
    maxReplicas: 5
    minReplicas: 0
  template:
    containers:
    - imagePullPolicy: IfNotPresent
      name: function
      resources: {}
  triggers:
    http:
      port: 8080
      route:
        gatewayRef:
          name: openfunction
          namespace: openfunction
  version: v1.0.0
```
