### ISSUE TITLE
functions/Knative/hello-world-go build failed

### ISSUE THREAD

**Issue by jingb** [OpenFunction/samples#23]
I have install openfunction controller, shipwright, knative-serving successfully.

NAME                                               READY   STATUS    RESTARTS   AGE
openfunction-controller-manager-85595fb5fb-4zf68   2/2     Running   1          75m
NAME                                           READY   STATUS    RESTARTS   AGE
shipwright-build-controller-664579bfc9-nwh54   1/1     Running   0          25m

NAME                                      READY   STATUS    RESTARTS   AGE
3scale-kourier-control-7c7cc7cbdd-gcr8x   1/1     Running   0          4h49m
activator-6677ff99b7-tx2cd                1/1     Running   0          4h49m
autoscaler-55c7df76d9-d9ptk               1/1     Running   0          4h49m
controller-68c85ff597-dckcv               1/1     Running   0          4h49m
default-domain-59lf7                      0/1     Error     0          79m
default-domain-76rtv                      0/1     Error     0          4h49m
default-domain-8qw6j                      0/1     Error     0          3h44m
default-domain-drrhk                      0/1     Error     0          3h
default-domain-jbmkh                      0/1     Error     0          4h6m
default-domain-kcjxg                      0/1     Error     0          3h22m
default-domain-m2wmv                      0/1     Error     0          153m
default-domain-nntjs                      0/1     Error     0          101m
default-domain-q9brz                      0/1     Error     0          4h27m
default-domain-qjc94                      0/1     Error     0          80m
default-domain-r24hr                      0/1     Error     0          127m
domain-mapping-7bc789d54-dnzcl            1/1     Running   0          4h49m
domainmapping-webhook-557cbfd6f5-4ckz6    1/1     Running   0          4h49m
webhook-7fd7cdb-gn82k                     1/1     Running   0          4h49m

I use the function yaml from the sameple and use my private registry 
And I already create the secret push-secret  
```
apiVersion: core.openfunction.io/v1alpha1
kind: Function
metadata:
  name: function-sample
spec:
  version: "v1.0.0"
  image: "myPrivateRegistry/sample-go-func:latest"  
  imageCredentials:
    name: push-secret
  #port: 8080 # default to 8080
  build:
    builder: openfunction/builder:v1
    env:
      FUNC_NAME: "HelloWorld"
      FUNC_TYPE: "http"
      #FUNC_SRC: "main.py"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/Knative/hello-world-go"
  serving:
    runtime: Knative
    template:
      containers:
        - name: function
          imagePullPolicy: Always
```

 
 kubectl get builder function-sample-builder-v7ncm
NAME                            PHASE   STATE    AGE
function-sample-builder-v7ncm   Build   Failed   12m

build failed and I cannot see any information via kubectl describe builder function-sample-builder-v7ncm
```
Status:
  Phase:  Build
  Resource Ref:
    shipwright.io/build:     function-sample-builder-v7ncm-build-xkpd5
    shipwright.io/buildRun:  function-sample-builder-v7ncm-buildrun-fnf7p
  State:                     Failed
Events:                      <none>
```
I could not find any useful message in shipwright-build-controller

shipwright-build log file below 

[shipwright-build-controller.log](https://github.com/OpenFunction/samples/files/7336161/shipwright-build-controller.log)
