### ISSUE TITLE
Function build failed for poor network

### ISSUE THREAD

**Issue by zhouqunjie-cs** [OpenFunction/samples#26]
I was trying to run demo logs-handler-function but it failed on step-create for golang connection problem,
![微信截图_20211101163109](https://user-images.githubusercontent.com/57168982/139643878-3fcccd8f-963d-401c-ae6d-bcddfc6f3518.png)
how to config goproxy in yaml?
can we add a option for poor network like --poor-network in OF?

**Comment by tpiperatgod** [comment]
You can pass the `FUNC_GOPROXY` in `spec.build.env` to set the goproxy:
```yaml
spec:
  version: "v1.0.0"
  image: openfunctiondev/logs-async-handler:v0.4.0
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/go115-builder:v0.3.0
    env:
      FUNC_NAME: "LogsHandler"
      FUNC_GOPROXY: "https://goproxy.cn,direct"
```
