### ISSUE TITLE
helloworld-go : no matches for kind "Function" in version "core.openfunction.io/v1beta1"

### ISSUE THREAD

**Issue by aBreaking** [OpenFunction/samples#46]
following [hello-world-go](https://github.com/OpenFunction/samples/tree/release-0.5/functions/Knative/hello-world-go), when i exec command 

```
kubectl apply -f function-sample.yaml
```

An error occurred :
```
error: unable to recognize "function-sample.yaml": no matches for kind "Function" in version "core.openfunction.io/v1beta1"
```

can help me? 

I just completely installed ofn. and  the pods of ofn components were running that i have checked. 
```
The following existing components will be skipped:
        - CertManager
        - IngressNginx
        - Dapr
        - Keda
        - Knative Serving
        - Tekton Pipelines
        - Shipwright
 ✓ Shipwright - Completed!
 ✓ OpenFunction - Completed!
🚀 Completed in 1m9.205258418s.

```

**Comment by tpiperatgod** [comment]
The `ofn` installs the latest stable version of OpenFunction (v0.5.0 for now) by default, with the branch of the corresponding sample as [release-0.5](https://github.com/openFunction/samples/tree/release-0.5).

Can you paste the contents of the `functions-sample.yaml`?

**Comment by aBreaking** [comment]
@tpiperatgod

functions-sample.yaml

```
apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-sample
spec:
  image: "abreaking/sample-go-func:latest"
```

and i also used [official yaml ](https://github.com/OpenFunction/samples/blob/main/functions/Knative/hello-world-go/function-sample.yaml) , also same error occurred.

my minikube version:

```
minikube v1.23.1
```

**Comment by tpiperatgod** [comment]
Hi, @aBreaking , you should use this yaml file: https://github.com/OpenFunction/samples/blob/release-0.5/functions/Knative/hello-world-go/function-sample.yaml

Note that `spec.build.srcRepo.revision` needs to be set to "release-0.5"
```yaml
apiVersion: core.openfunction.io/v1alpha2
kind: Function
metadata:
  name: function-sample
spec:
  version: "v1.0.0"
  image: "openfunctiondev/sample-go-func:v0.5"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: openfunction/builder-go:v0.4.0-1.15
    env:
      FUNC_NAME: "HelloWorld"
      FUNC_TYPE: "http"
    srcRepo:
      revision: "release-0.5"
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/Knative/hello-world-go"
  serving:
    runtime: Knative # default to Knative
#    template:
#      containers:
#       - name: function
#          # Set imagePullPolicy if needed
#          imagePullPolicy: Always
```
